"""Pipeline orchestrator for the RAG Comparison System.

Defines PipelineMethod (enum), RetrievalResult (dataclass), and the Pipeline
class that ties retrieval together with LLM answer generation.

Currently implemented:
    TRADITIONAL — dense retrieval from rag_traditional_v1 + LLM answer
    CONTEXTUAL  — dense retrieval from rag_contextualized_v1 + LLM answer
    HYBRID      — dense + BM25 + RRF fusion from rag_contextualized_v1 + LLM answer
    MODERN      — dense + BM25 + RRF + cross-encoder rerank + LLM answer
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from src.config import AppConfig
    from src.telemetry import TelemetryTracker

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_TRADITIONAL_COLLECTION = "rag_traditional_v1"
_CONTEXTUAL_COLLECTION = "rag_contextualized_v1"

_SYSTEM_PROMPT = (
    "You are a precise research assistant. "
    "Answer questions in 2-4 sentences only — concise and factual. "
    "No markdown headers, no bullet points, no numbered lists, no essays. "
    "Cite specific page numbers inline using (page N) format. "
    "Base your answer ONLY on the provided context. "
    "If the context lacks sufficient information, say so in one sentence."
)

_USER_PROMPT_TEMPLATE = """\
Context:
{context_block}

Question: {query}

Write a 2-4 sentence answer. Be concise and factual. Cite page numbers inline as (page N). No headers or bullet points."""


# ---------------------------------------------------------------------------
# Enum
# ---------------------------------------------------------------------------


class PipelineMethod(str, Enum):
    """The four retrieval methods under comparison."""

    TRADITIONAL = "traditional"
    CONTEXTUAL = "contextual"
    HYBRID = "hybrid"
    MODERN = "modern"


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass
class RetrievalResult:
    """Structured output from a single pipeline run."""

    query: str
    method: PipelineMethod
    retrieved_chunks: list[dict]
    answer: str
    sources: list[dict]          # [{doc, page}] deduplicated citations
    latency_ms: float
    telemetry_records: list      # LLMCallRecord objects recorded during this run
    input_tokens: int = 0        # prompt tokens consumed by _generate_answer LLM call
    output_tokens: int = 0       # completion tokens generated by _generate_answer LLM call


# ---------------------------------------------------------------------------
# Pipeline
# ---------------------------------------------------------------------------


class Pipeline:
    """Orchestrates retrieval + answer generation for a chosen pipeline method.

    Args:
        config:    AppConfig — all tunable parameters.
        telemetry: Optional TelemetryTracker.  When provided, LLM calls are
                   recorded automatically via the provider's _record_call helper.
                   Pass None to skip telemetry (e.g. in unit tests).
    """

    def __init__(
        self,
        config: "AppConfig",
        telemetry: "TelemetryTracker | None" = None,
    ) -> None:
        self.config = config
        self.telemetry = telemetry
        self._provider = None       # lazy-initialised on first run()
        self._bm25_index = None     # lazy-initialised on first _run_hybrid() call
        self._reranker = None       # lazy-initialised on first _run_modern() call

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def run(self, query: str, method: PipelineMethod) -> RetrievalResult:
        """Execute the full pipeline for *method* against *query*.

        Args:
            query:  Natural language question.
            method: Which retrieval pipeline to use.

        Returns:
            RetrievalResult with answer, sources, chunks, and latency.
        """
        logger.info("Pipeline.run start: method=%s query=%r", method.value, query[:80])
        t0 = time.perf_counter()

        if method == PipelineMethod.TRADITIONAL:
            chunks = self._run_traditional(query)
        elif method == PipelineMethod.CONTEXTUAL:
            chunks = self._run_contextual(query)
        elif method == PipelineMethod.HYBRID:
            chunks = self._run_hybrid(query)
        elif method == PipelineMethod.MODERN:
            chunks = self._run_modern(query)
        else:
            raise ValueError(f"Unknown PipelineMethod: {method!r}")

        answer, answer_input_tokens, answer_output_tokens = self._generate_answer(query, chunks, method)

        # Free MPS memory after Modern pipeline answer generation — reranker
        # (~1.1 GB) must not coexist with the embedder when the next query runs.
        if method == PipelineMethod.MODERN and self._reranker is not None:
            logger.info("Pipeline.run: unloading reranker after MODERN answer generation")
            self._reranker.unload()

        latency_ms = (time.perf_counter() - t0) * 1000

        sources = _extract_sources(chunks)

        # Collect any telemetry records added during this call.
        telemetry_records: list = []
        if self.telemetry is not None:
            # Snapshot the most-recently-added record(s).  The provider
            # records each call immediately after completion, so we grab
            # everything recorded since we started.
            telemetry_records = list(self.telemetry._records)

        logger.info(
            "Pipeline.run complete: method=%s latency_ms=%.1f chunks=%d answer_len=%d "
            "input_tokens=%d output_tokens=%d",
            method.value,
            latency_ms,
            len(chunks),
            len(answer),
            answer_input_tokens,
            answer_output_tokens,
        )

        return RetrievalResult(
            query=query,
            method=method,
            retrieved_chunks=chunks,
            answer=answer,
            sources=sources,
            latency_ms=round(latency_ms, 2),
            telemetry_records=telemetry_records,
            input_tokens=answer_input_tokens,
            output_tokens=answer_output_tokens,
        )

    # ------------------------------------------------------------------
    # Retrieval branches
    # ------------------------------------------------------------------

    def _run_traditional(self, query: str) -> list[dict]:
        """Dense retrieval from rag_traditional_v1."""
        from src.ingestion.store import get_or_create_collection
        from src.retrieval.dense import dense_retrieve

        logger.debug("_run_traditional: fetching collection '%s'", _TRADITIONAL_COLLECTION)
        collection = get_or_create_collection(_TRADITIONAL_COLLECTION, self.config)
        chunks = dense_retrieve(query, collection, self.config)
        logger.info("_run_traditional: retrieved %d chunks", len(chunks))
        return chunks

    def _run_contextual(self, query: str) -> list[dict]:
        """Dense retrieval from rag_contextualized_v1.

        Same retrieval logic as TRADITIONAL but queries the contextualized
        collection whose embeddings were enriched with LLM-prepended context.
        """
        from src.ingestion.store import get_or_create_collection
        from src.retrieval.dense import dense_retrieve

        logger.debug("_run_contextual: fetching collection '%s'", _CONTEXTUAL_COLLECTION)
        collection = get_or_create_collection(_CONTEXTUAL_COLLECTION, self.config)
        chunks = dense_retrieve(query, collection, self.config)
        logger.info("_run_contextual: retrieved %d chunks", len(chunks))
        return chunks

    def _run_hybrid(self, query: str) -> list[dict]:
        """Dense + BM25 + RRF fusion from rag_contextualized_v1.

        Steps:
            1. Dense retrieval (top_k_dense) from rag_contextualized_v1.
            2. BM25 retrieval (top_k_bm25) from the same collection.
               The BM25 index is built lazily on the first call and reused.
            3. RRF fusion of both ranked lists using config.retrieval.rrf_k.
            4. Return top_k_fusion results from the fused list.
        """
        from src.ingestion.store import get_or_create_collection
        from src.retrieval.dense import dense_retrieve
        from src.retrieval.bm25 import BM25Index
        from src.retrieval.fusion import reciprocal_rank_fusion

        cfg_r = self.config.retrieval

        # Step 1 — dense retrieval.
        logger.debug("_run_hybrid: step 1 — dense retrieval from '%s'", _CONTEXTUAL_COLLECTION)
        collection = get_or_create_collection(_CONTEXTUAL_COLLECTION, self.config)
        dense_chunks = dense_retrieve(
            query, collection, self.config, top_k=cfg_r.top_k_dense
        )
        logger.info("_run_hybrid: dense retrieved %d chunks", len(dense_chunks))

        # Step 2 — BM25 retrieval (lazy index build + cache).
        if self._bm25_index is None:
            logger.info(
                "_run_hybrid: BM25 index not yet built — building from '%s'",
                _CONTEXTUAL_COLLECTION,
            )
            self._bm25_index = BM25Index.build_from_collection(collection, self.config)
            logger.info("_run_hybrid: BM25 index ready")
        else:
            logger.debug("_run_hybrid: reusing cached BM25 index")

        bm25_chunks = self._bm25_index.search(query, top_k=cfg_r.top_k_bm25)
        logger.info("_run_hybrid: bm25 retrieved %d chunks", len(bm25_chunks))

        # Step 3 — RRF fusion.
        logger.debug(
            "_run_hybrid: step 3 — RRF fusion k=%d dense=%d bm25=%d",
            cfg_r.rrf_k,
            len(dense_chunks),
            len(bm25_chunks),
        )
        fused = reciprocal_rank_fusion(
            [dense_chunks, bm25_chunks],
            k=cfg_r.rrf_k,
        )
        logger.info("_run_hybrid: fused into %d unique chunks", len(fused))

        # Step 4 — take top_k_fusion results.
        top_chunks = fused[: cfg_r.top_k_fusion]
        logger.info(
            "_run_hybrid: returning top %d chunks (top_k_fusion=%d)",
            len(top_chunks),
            cfg_r.top_k_fusion,
        )
        return top_chunks

    def _run_modern(self, query: str) -> list[dict]:
        """Dense + BM25 + RRF fusion followed by cross-encoder reranking.

        Mirrors the Hybrid pipeline (dense retrieval from rag_contextualized_v1,
        BM25 retrieval, Reciprocal Rank Fusion) and adds a cross-encoder
        reranking step that re-scores each (query, chunk) pair with full attention,
        providing higher-quality relevance ordering than embedding similarity alone.

        The reranker is lazily initialised and cached on this Pipeline instance.
        After answer generation, run() calls reranker.unload() to free MPS memory.

        Returns top_k_rerank results sorted by cross-encoder score.
        """
        from src.ingestion.store import get_or_create_collection
        from src.retrieval.dense import dense_retrieve
        from src.retrieval.bm25 import BM25Index
        from src.retrieval.fusion import reciprocal_rank_fusion

        cfg_r = self.config.retrieval

        logger.info("_run_modern: dense + BM25 + RRF + rerank for query=%r", query[:80])

        # Step 1 — dense retrieval.
        logger.debug("_run_modern: step 1 — dense retrieval from '%s'", _CONTEXTUAL_COLLECTION)
        collection = get_or_create_collection(_CONTEXTUAL_COLLECTION, self.config)
        dense_chunks = dense_retrieve(query, collection, self.config, top_k=cfg_r.top_k_dense)
        logger.info("_run_modern: dense retrieved %d chunks", len(dense_chunks))

        # Step 2 — BM25 retrieval (lazy index build, shared cache with hybrid).
        if self._bm25_index is None:
            logger.info(
                "_run_modern: BM25 index not built — building from '%s'",
                _CONTEXTUAL_COLLECTION,
            )
            self._bm25_index = BM25Index.build_from_collection(collection, self.config)
            logger.info("_run_modern: BM25 index ready")
        else:
            logger.debug("_run_modern: reusing cached BM25 index")

        bm25_chunks = self._bm25_index.search(query, top_k=cfg_r.top_k_bm25)
        logger.info("_run_modern: bm25 retrieved %d chunks", len(bm25_chunks))

        # Step 3 — RRF fusion.
        logger.debug(
            "_run_modern: step 3 — RRF fusion k=%d dense=%d bm25=%d",
            cfg_r.rrf_k,
            len(dense_chunks),
            len(bm25_chunks),
        )
        fused = reciprocal_rank_fusion([dense_chunks, bm25_chunks], k=cfg_r.rrf_k)
        fused_top = fused[: cfg_r.top_k_fusion]
        logger.info(
            "_run_modern: RRF produced %d candidates (top_k_fusion=%d)",
            len(fused_top),
            cfg_r.top_k_fusion,
        )

        # Step 4 — Cross-encoder reranking.
        reranker = self._get_reranker()
        reranked = reranker.rerank(query, fused_top, top_k=cfg_r.top_k_rerank)
        logger.info("_run_modern: reranking complete, returning %d chunks", len(reranked))
        return reranked

    # ------------------------------------------------------------------
    # Answer generation
    # ------------------------------------------------------------------

    def _generate_answer(
        self,
        query: str,
        chunks: list[dict],
        method: PipelineMethod,
    ) -> str:
        """Build a prompt from retrieved chunks and call the LLM for an answer.

        Prompt structure:
            SYSTEM: instruction + citation guidance
            USER:   numbered context blocks + question

        Each context block is formatted as:
            [N] Source: <source_file>, Pages <page_start>-<page_end>
            <chunk text>

        Args:
            query:  Original query text.
            chunks: Retrieved chunk dicts from the retrieval branch.
            method: Pipeline method label (used for telemetry tagging).

        Returns:
            The LLM's answer as a plain string.
        """
        provider = self._get_provider()

        context_block = _format_context_block(chunks)
        user_prompt = _USER_PROMPT_TEMPLATE.format(
            context_block=context_block,
            query=query,
        )

        messages = [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        logger.debug(
            "_generate_answer: method=%s num_chunks=%d",
            method.value,
            len(chunks),
        )

        response = provider.complete(
            messages=messages,
            temperature=self.config.llm.temperature,
            max_tokens=self.config.llm.max_tokens,
        )

        # Record telemetry if available.
        if self.telemetry is not None:
            provider._record_call(response, "generate_answer", method.value)

        return response.text, response.input_tokens, response.output_tokens

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_provider(self):
        """Lazy-initialise and cache the LLM provider."""
        if self._provider is None:
            from src.llm import get_provider

            # get_provider requires a telemetry tracker; create a no-op
            # one if none was supplied so the provider can always call
            # _record_call without branching.
            telemetry = self.telemetry
            if telemetry is None:
                from src.telemetry import TelemetryTracker
                telemetry = TelemetryTracker(self.config)

            self._provider = get_provider(self.config, telemetry)
        return self._provider

    def _get_reranker(self):
        """Lazy-initialise and cache the CrossEncoderReranker."""
        if self._reranker is None:
            from src.retrieval.reranker import CrossEncoderReranker

            logger.info("Pipeline._get_reranker: initialising CrossEncoderReranker")
            self._reranker = CrossEncoderReranker(self.config)
        return self._reranker


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------


def _format_context_block(chunks: list[dict]) -> str:
    """Render a numbered list of chunk context blocks for the LLM prompt."""
    parts: list[str] = []
    for i, chunk in enumerate(chunks, start=1):
        source_file = chunk.get("source_file", "unknown")
        page_start = chunk.get("page_start", "?")
        page_end = chunk.get("page_end", "?")
        text = chunk.get("text", "").strip()
        parts.append(
            f"[{i}] Source: {source_file}, Pages {page_start}-{page_end}\n{text}"
        )
    return "\n\n".join(parts)


def _extract_sources(chunks: list[dict]) -> list[dict]:
    """Deduplicate and summarise source citations from retrieved chunks.

    Returns a list of ``{doc, page}`` dicts, one per unique
    (source_file, page_start) pair, ordered by appearance.
    """
    seen: set[tuple] = set()
    sources: list[dict] = []
    for chunk in chunks:
        source_file = chunk.get("source_file", "")
        page_start = chunk.get("page_start", 0)
        key = (source_file, page_start)
        if key not in seen:
            seen.add(key)
            sources.append({"doc": source_file, "page": page_start})
    return sources
